# Generated by Django 4.1.6 on 2023-02-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_direction_updated_at_product_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="direction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.direction",
            ),
            preserve_default=False,
        ),
    ]
