# Generated by Django 4.1.6 on 2023-02-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_product_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.status",
            ),
            preserve_default=False,
        ),
    ]
