# Generated by Django 4.1.6 on 2023-02-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0007_product_underlying"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="underlying",
            name="objectif",
        ),
        migrations.RemoveField(
            model_name="underlying",
            name="stop",
        ),
        migrations.AddField(
            model_name="product",
            name="objectif",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stop",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
