# Generated by Django 4.1.6 on 2023-02-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0008_remove_underlying_objectif_remove_underlying_stop_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="objectif",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stop",
        ),
    ]
