# Generated by Django 4.1.6 on 2023-02-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0009_remove_product_objectif_remove_product_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="objectif",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="stop",
            field=models.FloatField(default=0),
        ),
    ]
