# Generated by Django 4.1.6 on 2023-02-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0010_product_objectif_product_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="test",
            field=models.IntegerField(default=0),
        ),
    ]
