# Generated by Django 4.1.6 on 2023-02-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0011_product_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="test",
        ),
    ]
