# Generated by Django 4.1.6 on 2023-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0012_remove_product_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
