# Generated by Django 4.1.6 on 2023-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0013_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=7)),
            ],
        ),
    ]
