# Generated by Django 4.1.6 on 2023-02-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0014_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.currency",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=3),
        ),
    ]
