# Generated by Django 4.1.6 on 2023-02-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0015_product_currency_alter_currency_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="currency",
        ),
    ]
