# Generated by Django 4.1.6 on 2023-02-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0016_remove_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.currency",
            ),
            preserve_default=False,
        ),
    ]
