# Generated by Django 4.1.6 on 2023-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0017_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="underlying",
            name="memonic_code",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
